services:
  socket-relay-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3457:3457
    environment:
      - PORT=3457
    volumes:
      - ./public:/app/public
    restart: always
